export const weatherCode = {
  0: { emoji: "☀️", kondisi: "Cerah" },
  1: { emoji: "🌤️", kondisi: "Cerah Berawan" },
  2: { emoji: "⛅", kondisi: "Sebagian Berawan" },
  3: { emoji: "☁️", kondisi: "Mendung" },
  45: { emoji: "🌫️", kondisi: "Berkabut" },
  48: { emoji: "🌫️", kondisi: "Kabut Tebal" },
  51: { emoji: "🌦️", kondisi: "Gerimis Ringan" },
  53: { emoji: "🌦️", kondisi: "Gerimis Sedang" },
  55: { emoji: "🌧️", kondisi: "Gerimis Lebat" },
  56: { emoji: "🌧️", kondisi: "Gerimis Beku Ringan" },
  57: { emoji: "🌧️", kondisi: "Gerimis Beku Lebat" },
  61: { emoji: "🌧️", kondisi: "Hujan Ringan" },
  63: { emoji: "🌧️", kondisi: "Hujan Sedang" },
  65: { emoji: "🌧️", kondisi: "Hujan Lebat" },
  66: { emoji: "❄️", kondisi: "Hujan Beku Ringan" },
  67: { emoji: "❄️", kondisi: "Hujan Beku Lebat" },
  71: { emoji: "❄️", kondisi: "Salju Ringan" },
  73: { emoji: "❄️", kondisi: "Salju Sedang" },
  75: { emoji: "❄️", kondisi: "Salju Lebat" },
  77: { emoji: "🌨️", kondisi: "Kristal Salju" },
  80: { emoji: "🌦️", kondisi: "Hujan Lokal Ringan" },
  81: { emoji: "🌧️", kondisi: "Hujan Lokal Sedang" },
  82: { emoji: "🌧️", kondisi: "Hujan Lokal Lebat" },
  85: { emoji: "🌨️", kondisi: "Salju Lokal Ringan" },
  86: { emoji: "🌨️", kondisi: "Salju Lokal Lebat" },
  95: { emoji: "⛈️", kondisi: "Badai Petir" },
  96: { emoji: "⛈️⚡", kondisi: "Badai Petir + Hujan Es Ringan" },
  99: { emoji: "⛈️❄️", kondisi: "Badai Petir + Hujan Es Lebat" },
};